#!/usr/bin/lua


local openssl = require("openssl")

-- local key = openssl.gen_rsa_key(1024)
key=[[-----BEGIN ENCRYPTED PRIVATE KEY-----
MIIC1DBOBgkqhkiG9w0BBQ0wQTApBgkqhkiG9w0BBQwwHAQIXIrCqCtv6ucCAggA
MAwGCCqGSIb3DQIJBQAwFAYIKoZIhvcNAwcECGZzcEsDZ5iQBIICgMqE6OmYJv4/
TKxICGoZ3EKcTIjGxyeeYqgdbpNFWP7nP+ReX4Nw3GqWYYUt+4vuGqY2ZoMrN8yR
i+c+kxktQbbw7Pbo4OdkGZ5UvsrAYnh+93MD91gYvHZTdjQjTGpUanIgLvj4t/eK
albDRmPJjewH3HcdKZ4oZGS5dTCYdLXgG9bN8HBCELbCn1GQhr9TzwiPFWdTPUTe
Rz4aUPy6s22U1Ku8gB/dk+uRTKOW9j+0ylqJLcOuEVjn0qLXMBXDLabipnSffocH
sK4OeJPz3Um0fMPenihSaORopwK9o40trkijS++YxMRK1RTC6fNJfVr6FaRLTNLU
LiStYdETRFUh4RqbX59ddwzxSbbfSues7f3vPUMDScv37GiiI25EVBW8fIAHO7NQ
VLCeJ8t5cVpwjIrDqT13F3jHR8Sk+S4t56Y9teK1Cc4swz4UPZ4918cqtYsn5hMd
Ea8zBl7X1ADi9iEfbyweg5AEK52spgCQtLVUGOliaRIOPZ91gNpLJetXOmeULfmi
OGPK8bPfkyY5O5OFeUhd147NonKnowOCSvgtrjFlIkZv1BiTt35Xpx1nZGHEuF9k
6vzJt8ne0eNjgC3avfGmhGc4jiYMJ52PuJmggdEWWaHkzcTdsFABvqO2dvj8WMxH
P92nAXSuvBNvJqMQbYICSjJVgm1npuhso9wIOu/NnqcGCAJw93Pd9dJS+/yXCL6x
jK+rcA0a5Q8RBo1NZnz8hzaqfABGuke/CkY/ovVKyCs0c2qsXi/zQpgvcj6l9rhK
RVY6NcehXCvz9Shfx2QGaCDBptLfS5q//CnkZN7Vg/+/UQ7yK9lsNmPYSWvE3AT4
1Abi+Miv2ok=
-----END ENCRYPTED PRIVATE KEY-----]]
print(key)

-- local csr = openssl.gen_csr(key)
csr=[[-----BEGIN CERTIFICATE REQUEST-----
MIIBlTCB/wIBATBWMQswCQYDVQQGEwJDQTELMAkGA1UECAwCQkMxEjAQBgNVBAcM
CVZhbmNvdXZlcjESMBAGA1UECgwJRHluYW1zb2Z0MRIwEAYDVQQDDAlsb2NhbGhv
c3QwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAKveejYlQjO+9mPQobByYHqe
e6cMuQW+qCtoLB4WkXCZGuCsA7AFgYZ/nG1wLc8PM7IHSyomKuDSq2pD+4y+AwZw
cbIzDW5fEtYXakeTnn93DX3JvFeUa8poC5rypRKEw6cxrWIBDKsBf939epxI+ueb
7c8E+qbACTB7B++VPdUJAgMBAAGgADANBgkqhkiG9w0BAQsFAAOBgQCjSvbKpeg4
NwkFKM9xjbj2O9fRaWHAe6dg6e68tFOkT6VzMTdIQnVhKBfoaBuJE5myrAv+ZymU
2jPaqkaoUe1urtuoLKWuIMc3HzTW1Z6n7++BOMvOm6X2ygqppQOzXFFfGQJ0z0jZ
v+py3cAokqfgmTZe0mBvvdMEgjPMKkxM+w==
-----END CERTIFICATE REQUEST-----]]

print(csr)

-- local crt = openssl.gen_crt(key)

crt = [[-----BEGIN CERTIFICATE-----
MIICQTCCAaqgAwIBAgIBADANBgkqhkiG9w0BAQsFADBWMQswCQYDVQQGEwJDQTEL
MAkGA1UECAwCQkMxEjAQBgNVBAcMCVZhbmNvdXZlcjESMBAGA1UECgwJRHluYW1z
b2Z0MRIwEAYDVQQDDAlsb2NhbGhvc3QwHhcNMTkwNDI2MjIzODUxWhcNMjAwNDI1
MjIzODUxWjBWMQswCQYDVQQGEwJDQTELMAkGA1UECAwCQkMxEjAQBgNVBAcMCVZh
bmNvdXZlcjESMBAGA1UECgwJRHluYW1zb2Z0MRIwEAYDVQQDDAlsb2NhbGhvc3Qw
gZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAKveejYlQjO+9mPQobByYHqee6cM
uQW+qCtoLB4WkXCZGuCsA7AFgYZ/nG1wLc8PM7IHSyomKuDSq2pD+4y+AwZwcbIz
DW5fEtYXakeTnn93DX3JvFeUa8poC5rypRKEw6cxrWIBDKsBf939epxI+ueb7c8E
+qbACTB7B++VPdUJAgMBAAGjHzAdMBsGA1UdEQQUMBKCBmVjbi5pb4IIKi5lY24u
aW8wDQYJKoZIhvcNAQELBQADgYEAHqpZlflmK6fQt2kmoJ+JP0RwTe5yBF6cZPaa
bXsz1oA7GZvlfBgUoIxBZaHzZuE48dygt5dG3ub9EVIf4ErapIqqh9C9u9mIoq5S
L9tj+BJ5CWhEIRvNYDinl1OcoHCEaVYGisG6bCtVPmlY7P+W81+5fj9F5EYqIkeA
Jrhdhso=
-----END CERTIFICATE-----]]
print(crt)

local rc = openssl.init_crypto()

for idx = 1, 10, 1 do
  local crt1 = openssl.csr_crt(key, crt, csr)
  
  if crt1 == nil then
    print("Can't sign CSR\n")
  end
  
  print(crt1)
end  

